nginx:
  image: nginx:latest
  ports:
    - "8080:80"
    - "443:443"
  volumes:
    - ./www:/www
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./log:/var/log/nginx/
  links:
    - php

php:
  build: .
  volumes: 
    - ./www:/www
  links:
    - mariadb

mariadb:
  image: mariadb:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DB}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
    - "./db:/var/lib/mysql"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - mariadb:db
  ports:
    - "8082:80"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    PMA_USER: ${MYSQL_USER}
    PMA_PASSWORD: ${MYSQL_PASSWORD}
    UPLOAD_LIMIT: 1GB
    UPLOAD_MAX_FILESIZE: 1GB
    MAX_EXECUTION_TIME: 60000