nginx:
  image: nginx:latest
  ports:
    - "8080:80"
    - "443:443"
  volumes:
    - ./www:/www
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./log:/var/log/nginx/
  links:
    - php

php:
  build: .
  volumes: 
    - ./www:/www
#   - ./conf/php7.ini:/usr/local/etc/php/conf.d/my.ini:ro
#   - ./conf/php7-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
  links:
    - mariadb

#php8:
#  build: .
#  volumes: 
#   - ./www:/www
#   - ./conf/php8.ini:/usr/local/etc/php/conf.d/my.ini:ro
#   - ./conf/php8-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
#  links:
#    - mariadb

mariadb:
  image: mariadb:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
    - "./db:/var/lib/mysql"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - mariadb:db
  ports:
    - "8082:80"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    PMA_USER: ${MYSQL_USER}
    PMA_PASSWORD: ${MYSQL_PASSWORD}
    UPLOAD_LIMIT: 1GB
    UPLOAD_MAX_FILESIZE: 1GB
    MAX_EXECUTION_TIME: 60000

#wordpress:
#  depends_on:
#  - db
#  image: wordpress:latest
#  ports:
#  - '8000:80'
#  restart: always
#  volumes: 
#  - ./www:/var/www/html/
#  environment:
#    WORDPRESS_DB_HOST: ${MYSQL_DATABASE}
#    WORDPRESS_DB_NAME: ${MYSQL_DB}
#    WORDPRESS_DB_USER: ${MYSQL_USER}
#    WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
